### ISSUE TITLE
Rework graves generation at death

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Graves#289]
Graves generation logic should be splitted on 2 parts:
1) "death event" to get information about player and his death
2) "item drop event" to get items

As I guess such changes should allow collect any items from other mods slots, which should make some compatibility modules useless , and furthermore should allow to close some issues.

TODO:
- [ ] Split players graves generation logic 
- [ ] Create an items backup + console command to get them back(in case of any problems) #280 
- [ ] Do something at death in the void #281 
- [ ] Do something with grave generation inside some blocks blocks #256

Check are next sissues fixed or not:
- [ ] #274
- [ ] #270
- [ ] #269
- [ ] #257
- [ ] #252
- [ ] #250
